version: 2

jobs:
  build:
    docker:
      - image: docker:17.12.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login and setup
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build Docker image
          command: |
            docker build -f Dockerfile \
              --build-arg PHP_VERSION=7.2 \
              -t solomonjames/php:7.2 .
            docker push solomonjames/php:7.2
            