version: 2

jobs:
  build:
    docker:
      - image: docker:17.12.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login and setup
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build php7.2 Docker image
          command: |
            docker build -f Dockerfile \
              --build-arg PHP_VERSION=7.2 \
              -t iamksolo/php:7.2 .
            docker push iamksolo/php:7.2
      - run:
          name: Build php7.1 Docker image
          command: |
            docker build -f Dockerfile \
              --build-arg PHP_VERSION=7.1 \
              -t iamksolo/php:7.1 .
            docker push iamksolo/php:7.1
      - run:
          name: Build php7.0 Docker image
          command: |
            docker build -f Dockerfile \
              --build-arg PHP_VERSION=7.0 \
              -t iamksolo/php:7.0 .
            docker push iamksolo/php:7.0
